// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnibdrtxbrtvobqkqlmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuaWJkcnR4YnJ0dm9icWtxbG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDM1OTUsImV4cCI6MjA2OTk3OTU5NX0.uxAi_WOV37OAvK3-VjHmrzPdd86nxY5G3ncNdik34Kk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});